export const USER_LOGGED = 'USER_LOGGED'
export const CLEAR_LOGGED = 'CLEAR_LOGGED'
export const CURRENT_GROUP = 'CURRENT_GROUP'
export const PROGRESS_BAR = 'PROGRESS_BAR'
export const PROFILE = 'PROFILE'